---
title: "Questionnaire Summary"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 4,
  cache = FALSE)
```

```{r}
source("../functions_epic.R")
library(kableExtra)
```

```{r}
home_a <- read_rds("../output/questionnaires/home_answers.rds")
home_q <- read_rds("../output/questionnaires/home_questions.rds")

appliance_a <- read_rds("../output/questionnaires/appliance_answers.rds")
appliance_q <- read_rds("../output/questionnaires/appliance_questions.rds")
```

```{r}
n_homes <- length(unique(home_a$participant_id))
```

---

# Occupied Space

```{r}
df <- home_a %>%
  filter(q == 5) %>%
  group_by(answer) %>%
  count()

kable(df, caption = "Underground Space") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

```{r}
df <- home_a %>%
  filter(q == 6) %>%
  group_by(answer) %>%
  count()

kable(df, caption = "Roof Space") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

```{r}
df <- home_a %>%
  filter(q == 7) %>%
  group_by(answer) %>%
  count()

kable(df, caption = "Garage Space") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

---

# Residential History

```{r}
# duration
df <- home_a %>%
  ungroup() %>%
  filter(grepl("^22$|^23$|^24$", q)) %>%
  filter(!grepl("0", answer)) %>%
  select(participant_id, answer, q) %>%
  mutate(years = round(as.numeric(answer) / 12, 0),
         q = if_else(q == "22", "current address", q),
         q = if_else(q == "23", "prior address", q),
         q = if_else(q == "24", "prior to previous address", q)) %>%
  select(-answer)
```

```{r}
# rent or own
df_2 <- home_a %>%
  ungroup() %>%
  filter(grepl("^25$|^26$|^27$", q)) %>%
  select(participant_id, answer, q) %>%
  mutate(q = if_else(q == "25", "current address", q),
         q = if_else(q == "26", "prior address", q),
         q = if_else(q == "27", "prior to previous address", q)) %>%
  rename("rent_own" = "answer")
```

```{r}
# combine data
df_3 <- df %>%
  left_join(df_2, by = c("participant_id", "q")) %>%
  na.omit()
```

```{r, fig.width = 5}
ggplot(df_3, aes(x = years)) +
  geom_histogram(color = "grey15", fill = "grey85") +
  theme_bw() +
  facet_wrap(~q+rent_own, ncol = 2) +
  xlab("Years living at address") +
  ylab("n") +
  scale_y_continuous(breaks = seq(0, 12, 3)) +
  ggtitle("Years living at past three addresses")
```

---

# Ventilation

```{r}
df <- home_a %>%
  filter(q == 85) %>%
  group_by(answer) %>%
  count() %>%
  ungroup() %>%
  mutate(pct = round(100 * n / n_homes, 0))

kable(df, caption = "Kitchen Ventilation") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

```{r}
df <- home_a %>%
  filter(q == 90) %>%
  group_by(answer) %>%
  count() %>%
  ungroup() %>%
  mutate(pct = round(100 * n / n_homes, 0))

kable(df, caption = "Bathroom Ventilation") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

---

# Smoking

```{r}
# indoor smoking
df_1 <- home_a %>%
  filter(grepl("^102$|^103$|^104$|^105$|^106$", q)) %>%
  mutate(answer = as.numeric(answer)) %>%
  group_by(participant_id) %>%
  summarise(smoke = sum(answer, na.rm = TRUE), .groups = "drop") %>%
  mutate(smoke_yn = if_else(smoke > 0, "yes", "no")) %>%
  group_by(smoke_yn) %>%
  count()
  
kable(df_1, caption = "Indoor smoking reported") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

```{r}
# outdoor smoking
df_2 <- home_a %>%
  filter(grepl("^108$|^109$|^110$|^111$|^112$", q)) %>%
  mutate(answer = as.numeric(answer)) %>%
  group_by(participant_id) %>%
  summarise(smoke = sum(answer, na.rm = TRUE), .groups = "drop") %>%
  mutate(smoke_yn = if_else(smoke > 0, "yes", "no")) %>%
  group_by(smoke_yn) %>%
  count()
  
kable(df_2, caption = "Outdoor smoking reported") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

```{r}
# indoor smoking frequency
df_3 <- home_a %>%
  filter(grepl("^113$|^114$|^115$|^116$|^117$", q)) %>%
  mutate(answer = factor(answer, levels = c("daily", "weekly", "monthly", "rarely", "never"))) %>%
  group_by(participant_id) %>%
  arrange(participant_id, answer) %>%
  summarise(answer = first(answer), .groups = "drop") %>%
  group_by(answer) %>%
  count()

kable(df_3, caption = "Indoor smoking frequency reported") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

```{r}
# outdoor smoking frequency
df_4 <- home_a %>%
  filter(grepl("^118$|^119$|^120$|^121$|^122$", q)) %>%
  mutate(answer = factor(answer, levels = c("daily", "weekly", "monthly", "rarely", "never"))) %>%
  group_by(participant_id) %>%
  arrange(participant_id, answer) %>%
  summarise(answer = first(answer), .groups = "drop") %>%
  group_by(answer) %>%
  count()

kable(df_4, caption = "Outdoor smoking frequency reported") %>%
kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

---
