---
title: "Time Series Cameron Peak Plots"
author: "Andrew Purgiel"
date: "7/22/2021"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

---

```{r libraries}
library(dplyr)
library(purrr)
library(tidyr)
library(openair)
library(ggplot2)
library(readr)
library(googlesheets4)
library(lubridate)
library(gridExtra)
# library(tidymodels) # to discretize data for histogram
library(arules) # to discretize data for histogram
```

```{r data_import}
omni_hourly <- read_rds('./csv_created_article/omni_hourly_calibrated.rds') %>%
  rename(datetime = datehour)

home_type_df <- read_csv('../sense/csv_created_sense_article/home_type_df.csv')
```

# only use data up to June 2021
# and rename noise variable
```{r censor_date}
omni_hourly <- omni_hourly %>% filter(datetime<ymd_hms('2021-06-01 00:00:00'))%>%
  rename('noise' = spl_a)


```


```{r functions_misc}

 # misc------------------------------------------------

##Define a char vector of home numbers using a number vector,
##ex: x <- home.list(c(1:15)) for homes 1-15
threedig <- function(x) {
  if (nchar(x) == 1) {a <- paste0('00', x)
  return(a)
  }
  
  if (nchar(x) == 2) {a<- paste0('0', x)
  return(a)
  }
  else return(a)
}

home.list <- function(x) sapply(x, threedig)


 # function to extract a legend from one plot for use in whole plot grid
 # reference: https://stackoverflow.com/questions/13649473/add-a-common-legend-for-combined-ggplots
 g_legend<-function(a.gplot){
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)}
 



#Mean and sd functions to ignore NA values
mean_NA <- function(x, na.rm = na.rm) {
  mean(x, na.rm = TRUE)}

sd_NA <- function(x, na.rm = na.rm) {
  sd(x, na.rm = TRUE)}

#Function to only display 3 significant figures (for tables)
signif3 <- function(x){
  signif(x, digits = 3)
}



#Function found online for geometric mean to use for plots
#webpage: https://stackoverflow.com/questions/2602583/geometric-mean-is-there-a-built-in
#adjusted so zeros are not ignored, just added one, to all values and subtract at end
#adjusted "length" to ignore values that are NA


gm = function(x, na.rm=TRUE){
  if(any(x < 0, na.rm = TRUE)){
    return(NaN)
  }
  if(any(x == 0, na.rm = TRUE)){
    exp(sum(log(x+1), na.rm=na.rm) / length(x[!is.na(x)]))-1
  }
  else {
    exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x[!is.na(x)]))
  }
}



#make low and high sd "interval" functions
low.sd = function(x){
  mean_NA(x)-sd_NA(x)
}

high.sd = function(x){
  mean_NA(x)+sd_NA(x)
}


#create function for standard error
std.error = function(x, na.rm=TRUE){
  sd_NA(x)/sqrt(length(x[!is.na(x)]))
}

##make low and high 95% conf interval (default 95%)
low.conf = function(x){
  gm(x)-1.96*std.error(x)
}

high.conf = function(x){
  gm(x)+1.96*std.error(x)
}





# labeller

# make function to label metric names with subscripts and seasons
labeller.all <- as_labeller(c(
  'pm25'='PM[2.5]', 'voc'="TVOC",
  'co2' = 'CO[2]', 'temp' = 'Temperature', 'humid' = 'Humidity',
  'lux' = 'Light', 'spl_a' = 'Noise',
  'ac' = 'Cooling', 'shoulder' = 'Shoulder', 'heat' = 'Heating',
  'kitchen' = 'Kitchen', 'living' = 'Living', 'bedroom' = 'Bedroom',
  'outdoor' = 'Outdoor', 'garage'= 'Garage',
  'cam_peak' = 'Cameron Peak Fire Effects', 'no_cam_peak' = 'Negligible Cameron Peak Fire Effects'
  ), default = label_parsed)
  
```



# function for making data at given time averaging periods
```{r}
##Function to make table for plots of real time OMNI data
##averaged by hour of day, weekday, month, or a combination
time.table <- function(data, period, met,
                       start_date = "1900-01-13 00:00:00",
                       end_date = "9999-08-13 00:00:00",
                       groupers = NULL, # vector of variables to group by
                       # arithmetic mean if FALSE, geometric if TRUE 
                       geometric = FALSE,
                       error = 'conf'
                       ) {
  
  #use start and end date to define timespan during which to use data
  a <- data %>%
    filter(datetime > ymd_hms(start_date) &
             datetime < ymd_hms(end_date)) %>%
    select(datetime, home, location, all_of(met), energy_cluster, period)
  
  #if geo is FALSE (default), use arithmetic mean and standard deviation
  #to plot line and error bars respectively
  #if geo is TRUE, use geometric mean and 95% conf interval
  #to plot line and error bars respectively
  if(geometric == FALSE){
    mean.val <- function(x) {mean(x, na.rm = TRUE)}

  } else if(geometric == TRUE){
    mean.val <- function(x) {gm(x)}

  }
  
  if(error == 'conf'){
    high.val <- function(x) {
      mean.val(x)+1.96*sd(x, na.rm = TRUE)/sqrt(length(x[!is.na(x)]))
    }
    low.val <- function(x) {
      mean.val(x)-1.96*sd(x, na.rm = TRUE)/sqrt(length(x[!is.na(x)]))
    }
} else if(error == 'sd'){
    high.val <- function(x) mean.val(x)+sd(x, na.rm = TRUE)
    low.val <- function(x) mean.val(x)-sd(x, na.rm = TRUE)
 }
  
  #####average and plot values by the specified time period
  #hour of day
  if (period == 'hour'){

    # average and plot values by hour of day
    a <- a %>%
      mutate(hour = hour(datetime))
    
    a <- a %>%
      group_by_at(.vars= c('hour', groupers)) %>%
      summarize_if(is.numeric, list(mean.val = mean.val,
                                    low.val = low.val,
                                    high.val = high.val)) %>%
      ungroup() %>%
      left_join(
        a %>%
          group_by_at(.vars= c('hour', groupers)) %>%
      summarize(n = n(), .groups = 'drop'),
      by = c('hour', groupers)
      )%>%
      mutate(hour = as.numeric(hour)
             ) %>% 
      mutate(metric = met)
    
      }
  
  #weekday
  if (period == 'day'){
    a <- a %>%
      mutate(weekday = wday(datetime, label = TRUE))
    
    a <- a %>%
      group_by_at(.vars= c('weekday', groupers)) %>%
      summarize_if(is.numeric, list(mean.val = mean.val,
                                    low.val = low.val,
                                    high.val = high.val)) %>%
      ungroup() %>%
      left_join(
        a %>%
          group_by_at(.vars= c('weekday', groupers)) %>%
      summarize(n = n(), .groups = 'drop'),
      by = c('weekday', groupers),
      )%>%
      mutate(metric = met)
    
  }
  
  
    #weekday
  if (period == 'month'){
    a <- a %>%
      mutate(month = floor_date(datetime, unit = 'month'))
    
    a <- a %>%
      group_by_at(.vars= c('month', groupers)) %>%
      summarize_if(is.numeric, list(mean.val = mean.val,
                                    low.val = low.val,
                                    high.val = high.val)) %>%
      ungroup() %>%
      left_join(
        a %>%
          group_by_at(.vars= c('month', groupers)) %>%
      summarize(n = n(), .groups = 'drop'),
      by = c('month', groupers),
      )%>%
      mutate(metric = met)
    
  }
  
  return(a)

}
```


# define variables
```{r define_variables}

##For plot labeling pruposes
xsmall <- 6
small <- 15
medium <- 20
large <- 26
line_size <- 0.5
max_point_size <- 0.75

# define y-limits for metrics (for time series plots)
pm25_lim <- c(0,60)
voc_lim <- c(0,1500)
co2_lim <- c(0,2500)
temp_lim <- c(0,25)
humid_lim <- c(0,60)
lux_lim <- c(0,1000)
noise_lim <- c(40,70)

# define y-limits for metrics (for difference of means plots)
pm25_diff_lim <- c(-23,20)
voc_diff_lim <- c(-300,500)
co2_diff_lim <- c(-600,1250)
temp_diff_lim <- c(-5,3.5)
humid_diff_lim <- c(-9,9)
lux_diff_lim <- c(-500,750)
noise_diff_lim <- c(-9,9)

## for zoom:
#   pm25_lim <- c(0,40)
# voc_lim <- c(0,1000)
# co2_lim <- c(0,1500)
# temp_lim <- c(15,25)
# humid_lim <- c(20,60)
# lux_lim <- c(0,500)
# spl_a_lim <- c(40,70)




homes_all <- home.list(c(1:16))
homes_no5 <- home.list(c(1:4, 6:16))
homes_tier1 <- home_type_df %>% filter(home_type == 'tier1') %>% pull(home)
homes_tier2 <- home_type_df %>% filter(home_type == 'tier2') %>% pull(home)
homes_tier3 <- home_type_df %>% filter(home_type == 'tier3') %>% pull(home)

metrics_all <- c('pm25', 'voc', 'co2', 'temp','humid', 'lux', 'spl_a')
locations_indoor <- c('living', 'bedroom', 'kitchen')

periods_all <- c('hour', 'day', 'month')

living_data <- omni_hourly %>% filter(location == 'living')
kitchen_data <- omni_hourly %>% filter(location == 'kitchen')
bedroom_data <- omni_hourly %>% filter(location == 'bedroom')
outdoor_data <- omni_hourly %>% filter(location == 'outdoor')
garage_data <- omni_hourly %>% filter(location == 'garage')


# color blind pallette
# check http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbbPalette <- c('black' = "#000000",
                'light_orange' = "#E69F00",
                'light_blue' = "#56B4E9",
                'green' = "#009E73",
                'yellow' = "#F0E442",
                'dark_blue' = "#0072B2",
                'dark_orange' = "#D55E00",
                'purple' = "#CC79A7"
                )
# define colors for room-comparisons
room_colors <- c(cbbPalette['green'],
                   cbbPalette['purple'],
                   cbbPalette['light_orange']
                   )%>% unname()

room_breaks <- locations_indoor

room_labels <- c('Living Room', 'Bedroom', 'Kitchen')

# define colors for energy clusters
energy_colors <- c(cbbPalette['light_blue'],
                   cbbPalette['green'],
                   cbbPalette['dark_orange'],
                   cbbPalette['black'])%>% unname()

energy_breaks <- c('ac', 'shoulder', 'heat', 'overall')
energy_labels <- c('Cooling', 'Shoulder', 'Heating', 'Entire Period')


# define colors for fire periods
period_colors <- c(cbbPalette['light_orange'],
                   cbbPalette['dark_blue'])%>% unname()

period_breaks <- c('cam_peak', 'no_cam_peak')
period_labels <- c( 'Cameron Peak\nFire Effects', 'Negligible Cameron\nPeak Fire Effects'
)
```


# define data with and without Cam Peak fire effects
# use AUgust 13th (start date of fire)
# through November 1st (October was last month in which elevated PM2.5) were observed
```{r}

omni_hourly <- omni_hourly %>%
  mutate( period = case_when(
    datetime > ymd_hms('2020-08-12 23:59:59') & 
           datetime < ymd_hms('2020-10-31 23:59:59')   ~ 'cam_peak',
    datetime < ymd_hms('2020-08-12 23:59:59') |
          datetime > ymd_hms('2020-10-31 23:59:59')   ~  'no_cam_peak'
  ))


```



## By fire Season

### function
```{r}

   # plot disag by season, facet by room and etric
      plot.hourly.seasons <- function(data, n_homes) {
     
        
 # make a dummy df in which to define limits for each metric
limit_df <-
      data %>%
  group_by( metric) %>%
  summarize(max = max(mean.val))%>%
  mutate(min = 0) %>%
        pivot_longer(cols = c(max, min), names_to = 'side', values_to = 'limits')


      ### plot
     ggplot(data, aes(x = hour, y = mean.val))+
    geom_line( aes(color = period), size = line_size)+
    #geom_errorbar(aes(ymax = high.val, ymin = low.val))+ ##bars instead?
    geom_ribbon(aes(ymax = high.val,
                    ymin = low.val, fill = period),
                alpha = 0.2, color = NA)+
        labs(
          y = 'Average Value',
             x = 'Hour of Day',
          color= 'Time Period',
          fill = 'Time Period',
          size = 'Sensor-Hours\nof Data')+
       
    scale_x_continuous(limits = c(0,24),
                       breaks = c(0,6,12,18),
                       labels = c('12am', '6am','12pm', '6pm'),
                       expand = c(0,0))+
    theme_bw()+
       # guides(col = guide_legend(ncol = 2))+ #split up legend
          ##for extra space between facets
    theme(
          strip.background =element_blank(),
      strip.text = element_text(size = small),
      legend.text = element_text(size = small),
            legend.title = element_text(size = small),
      axis.text = element_text(size = small - 2),
      axis.title = element_text(size = small),
      legend.spacing.y = unit(0.1, 'in') # allow extra space between legend items
      )+
       facet_grid(c('metric', 'location'))+
        # make point size proportional to # of obs, with 0 obs = size 0
      geom_point(aes(size = n, color = period))+
        scale_size_area(max_size = max_point_size+0.5,
                        )+
        facet_wrap(vars(metric), nrow = 1, labeller = labeller.all,
                   scales = 'free_y')+

        # use dummy df to define limits for each metric
        geom_blank(data = limit_df, aes(x = 15, y = limits))+
               #ensure seaons legend on top
        guides(
    fill = guide_legend(order = 1,
                        byrow = T # allow extra space between legend items
                        ), 
        color = guide_legend(order = 1,
                             byrow = T# allow extra space between legend items
                             ),
    size = guide_legend(order = 2)
  )+
        labs(tag = paste('*n homes =', n_homes) )+
      theme(
        plot.tag.position = c(.1,0.02),
        )+
                scale_fill_manual(
          breaks = period_breaks,
          values = period_colors,
          labels = period_labels,
          aesthetics = c('fill', 'color')
        )
     }


```

###Plot for outdoor
```{r, fig.height=2.5, fig.width=8}


a <- map(c('pm25', 'voc', 'co2', 'temp'), function(x_metric){
  
  dat <- omni_hourly %>% filter (
    location == 'outdoor'
  )
  
  time.table(dat, 'hour', x_metric, groupers = c('period'))
}
) %>% bind_rows()

# change order of metrics for plotting
a$metric <- factor(a$metric, levels = c('pm25', 'voc', 'co2', 'temp'))



# plot
plot.hourly.seasons(data = a, n_homes = omni_hourly %>% pull(home) %>% factor() %>% levels() %>% length())


```


###Plot for indoor rooms pooled
```{r, fig.height=2.5, fig.width=8}


a <- map(c('pm25', 'voc', 'co2', 'temp'), function(x_metric){
  
  dat <- omni_hourly %>% filter (
    location %in% c('kitchen', 'living', 'bedroom')
  )
  
  time.table(dat, 'hour', x_metric, groupers = c('period'))
}
) %>% bind_rows()

# change order of metrics for plotting
a$metric <- factor(a$metric, levels = c('pm25', 'voc', 'co2', 'temp'))



# plot
plot.hourly.seasons(data = a, n_homes = omni_hourly %>% pull(home) %>% factor() %>% levels() %>% length())


```


