---
title: "Import and Clean Omni Data"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

---

```{r}
library(dplyr)
library(purrr)
library(tidyr)
library(openair)
library(ggplot2)
library(readr)
library(googlesheets4)
library(lubridate)
library(data.table)
library(kableExtra)
```

```{r define_variables}
#define the homes that will be used later in analysis
homes_no5 <- c(
  map(c(1:4,6:9), function(x) paste0('00', x)),
  map(c(10:16), function(x) paste0('0', x))
  )%>% unlist()


##For plot labeling pruposes
xsmall <- 6
small <- 15
medium <- 20
large <- 26

# color blind pallette
# check http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbbPalette <- c('black' = "#000000",
                'light_orange' = "#E69F00",
                'light_blue' = "#56B4E9",
                'green' = "#009E73",
                'yellow' = "#F0E442",
                'dark_blue' = "#0072B2",
                'dark_orange' = "#D55E00",
                'purple' = "#CC79A7"
                )
# define colors for room-comparisons
location_colors <- c(cbbPalette['green'],
                   cbbPalette['purple'],
                   cbbPalette['light_orange'],
                   cbbPalette['dark_blue'],
                   cbbPalette['dark_orange']
                   )%>% unname()

 location_shapes <- c(16, 17, 15, 7, 13) 


location_breaks <- c('living', 'bedroom', 'kitchen', 'garage', 'outdoor')

location_labels <- c('Living Room', 'Bedroom', 'Kitchen', 'Garage', 'Outdoor')



```


# Clean minutely data


```{r import_all_data, eval = FALSE}

omni_data <- read_rds(paste0('./csv_created_article/pre-calibration/omni_all_locations_raw.rds'))

```

# only use data up to June 2021
```{r censor_date, eval = FALSE}
omni_data <- omni_data %>% filter(datetime<ymd_hms('2021-06-01 00:00:00'))

```


# find and remove (or average) duplicates
# and create rds file of uncalibrated data

```{r clean_data, eval = FALSE}

# clean duplicates from sensor overlaps----------
 
 # remove home 003 outdoor from March 21 to March 23
# when temp was above 15 (from overlap with living room sensor)
omni_data_clean <- omni_data %>%
    filter(!(home=='003' & location == 'outdoor'&
             between(datetime, ymd_hms('2021-03-21 17:59:00'),
                     ymd_hms('2021-03-23 23:59:59')) &
                     temp >15))

  # average dupicates in home 009 living due to sensor overlap
 a <- omni_data_clean %>%
    filter(!(home=='009' & location == 'living'))


b <- omni_data_clean %>%
  filter(home=='009', location == 'living') %>%
    group_by(datetime, home, location) %>% 
    summarise_if(is.numeric, list(mean), na.rm = TRUE, .groups = 'drop')

omni_data_clean <- bind_rows(a,b)

  # average dupicates in home 003 living due to sensor overlap
 a <- omni_data_clean %>%
    filter(!(home=='003' & location == 'living'))


b <- omni_data_clean %>%
  filter(home=='003', location == 'living') %>%
    group_by(datetime, home, location) %>% 
    summarise_if(is.numeric, list(mean), na.rm = TRUE, .groups = 'drop')


omni_data_clean <- bind_rows(a,b)
 


# delete duplicates from pm10_est addition------------

# from april 7 to april 15 there are some nearly identical values

 a <- omni_data_clean %>%
    filter(!between(datetime, ymd_hms('2021-04-07 00:00:00'),
                     ymd_hms('2021-04-15 23:59:59')))


b <- omni_data_clean %>%
  filter(between(datetime, ymd_hms('2021-04-07 00:00:00'),
                     ymd_hms('2021-04-15 23:59:59')))


b <- b %>%
    group_by(datetime, home, location) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE, .groups = 'drop')


# merge and delete pm10_est col
omni_data_clean <- bind_rows(a,b) %>%
  select(-pm10_est)


# average duplicates from daylight savings------------

# use data.table to count duplicates
b_dt <- omni_data_clean %>%  data.table()

a <-  (b_dt[, count:= .N,
            by = omni_data_clean %>% select(c(datetime, home, location)) ]) %>%
  as.data.frame()

# unique rows
unique<- a %>%
  filter(count == 1) %>%
  select(-count)

# duplicate rows
duplicates<- a %>%
  filter(count >1) %>%
  select(-count)

# average duplicates that are from daylight savings
avg_daylight <-  duplicates %>%
  filter(between(datetime, ymd_hms("2020-10-31 23:59:00"),
                                ymd_hms("2020-11-01 01:59:00"))) %>%
  group_by(datetime, home, location) %>% 
  summarise_if(is.numeric, mean) %>%
  ungroup()


duplicates_no_daylight <-  duplicates %>%
  filter(!between(datetime, ymd_hms("2020-10-31 23:59:00"),
                                ymd_hms("2020-11-01 01:59:00"))) 
  

  # combine rows into dataframe without duplicates
 omni_data_clean <- bind_rows(unique,duplicates_no_daylight,avg_daylight)
  
 # test to ensure no duplicates are remaining (should be no rows)----------
 
 if(nrow(duplicates_no_daylight)>0) {
stop('duplicates outside of daylight savings time exist')}


 # omit unrealistic temperatures-------------

  omni_data_clean <- omni_data_clean %>%
  mutate(temp = ifelse(temp > 100, NA, temp))

 
 # copy outdoor data for outdoor duplex units ----------------
 omni_data_clean <- omni_data_clean %>%
   bind_rows(
     omni_data_clean %>%
               filter(home == '014' & location == 'outdoor') %>%
               mutate(home = '013'),
     omni_data_clean %>%
               filter(home == '015' & location == 'outdoor') %>%
               mutate(home = '016')
     )

  # write data and backup------------------- 

write_rds(omni_data_clean, paste0('./csv_created_article/pre-calibration/omni_all_locations_pre-cal_', Sys.Date(), '.rds'))

write_rds(omni_data_clean, paste0('./csv_created_article/pre-calibration/omni_all_locations_pre-cal.rds'))
 
```


# create data of multiple resolutions from cleaned data
# and create rds files

```{r hourly_data_rds, eval = FALSE}

omni_hourly_data <- omni_data_clean %>%
  group_by(datehour = floor_date(datetime, unit = 'hour'),
           home, location) %>%
  summarise_if(is.numeric, list(mean), na.rm = TRUE) %>%
  ungroup()

# make csv and backup------------------------

write_rds(omni_hourly_data, paste0('./csv_created_article/pre-calibration/omni_hourly_data_pre-cal_',
Sys.Date(),'.rds'))

write_rds(omni_hourly_data, paste0('./csv_created_article/pre-calibration/omni_hourly_data_pre-cal.rds'))

```

```{r daily_data_rds, eval = FALSE}

  omni_daily_data <- omni_data_clean %>%
  group_by(dateday = floor_date(datetime, unit = 'day'),
           home, location) %>%
  summarise_if(is.numeric, list(mean), na.rm = TRUE) %>%
  ungroup()

# make csv and backup------------------------
write_rds(omni_daily_data, paste0('./csv_created_article/pre-calibration/omni_daily_data_pre-cal_',
Sys.Date(),'.rds'))

write_rds(omni_daily_data, paste0('./csv_created_article/pre-calibration/omni_daily_data_pre-cal.rds'))

```
