---
title: "Compare thesis and article Omni Data"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

---

```{r}
library(dplyr)
library(purrr)
library(tidyr)
library(openair)
library(ggplot2)
library(readr)
library(googlesheets4)
library(lubridate)
library(data.table)
library(kableExtra)
```

```{r define_variables}
#define the homes that will be used later in analysis
homes_no5 <- c(
  map(c(1:4,6:9), function(x) paste0('00', x)),
  map(c(10:16), function(x) paste0('0', x))
  )%>% unlist()


##For plot labeling pruposes
xsmall <- 6
small <- 15
medium <- 20
large <- 26

# color blind pallette
# check http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbbPalette <- c('black' = "#000000",
                'light_orange' = "#E69F00",
                'light_blue' = "#56B4E9",
                'green' = "#009E73",
                'yellow' = "#F0E442",
                'dark_blue' = "#0072B2",
                'dark_orange' = "#D55E00",
                'purple' = "#CC79A7"
                )
# define colors for room-comparisons
location_colors <- c(cbbPalette['green'],
                   cbbPalette['purple'],
                   cbbPalette['light_orange'],
                   cbbPalette['dark_blue'],
                   cbbPalette['dark_orange']
                   )%>% unname()

 location_shapes <- c(16, 17, 15, 7, 13) 


location_breaks <- c('living', 'bedroom', 'kitchen', 'garage', 'outdoor')

location_labels <- c('Living Room', 'Bedroom', 'Kitchen', 'Garage', 'Outdoor')



```


# calibrate uncalibrated data sued for thesis and article

```{r import_uncalibrated_data}
# data for article\

omni_data_precal <- 
  # read in uncalibrated data
  read_rds(paste0('./csv_created_article/pre-calibration/omni_all_locations_pre-cal.rds')) %>%
  filter(home %in% homes_no5)

# data for thesis

omni_data_precal_thesis <-
  # read in uncalibrated data
  read_rds(paste0('../../omni/csv_created/pre-calibration/omni_all_locations_pre-cal.rds')) %>%
  filter(home %in% homes_no5)

```



* compare start and end dates before editing thesis data
```{r}
# compare start and end dates of
# pre-cal data from thesis and article
thesis_dates <- omni_data_precal_thesis %>%
  group_by(home) %>%
  summarize(start = min(datetime),
         end = max(datetime),
         .groups = 'drop')

article_dates <- omni_data_precal %>%
  group_by(home) %>%
  summarize(start = min(datetime),
         end = max(datetime),
         .groups = 'drop')

```


* omit data after may 31 from thesis data and compare to article data
```{r}
# compare start and end dates of
# pre-cal data from thesis and article
thesis_data_edit <- omni_data_precal_thesis %>%
  filter(datetime<ymd_hms('2021-06-01 00:00:00'))

thesis_dates_edit <- thesis_data_edit %>%
  group_by(home) %>%
  summarize(start = min(datetime),
         end = max(datetime),
         .groups = 'drop')

#check dates are equal
all.equal(thesis_dates_edit, article_dates)

# check data sets are equal
all.equal(thesis_data_edit, omni_data_precal)


```
