---
title: "Time Series Summary Plots"
author: "Andrew Purgiel"
date: "7/22/2021"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

---

```{r libraries}
library(dplyr)
library(purrr)
library(tidyr)
library(openair)
library(ggplot2)
library(readr)
library(googlesheets4)
library(lubridate)
library(gridExtra)
# library(tidymodels) # to discretize data for histogram
library(arules) # to discretize data for histogram
```

```{r data_import}
# hourly omni data
omni_hourly <- read_rds('./csv_created_article/omni_hourly_calibrated.rds') %>%
  rename(datetime = datehour) %>%
  filter(datetime<ymd_hms('2021-06-01 00:00:00'))%>% # only use data up to June 2021
  rename('noise' = spl_a) # and rename noise variable

# home groups
home_type_df <- read_csv('../sense/csv_created_sense_article/home_type_df.csv')
```


```{r functions_misc}

 # misc------------------------------------------------

##Define a char vector of home numbers using a number vector,
##ex: x <- home.list(c(1:15)) for homes 1-15
threedig <- function(x) {
  if (nchar(x) == 1) {a <- paste0('00', x)
  return(a)
  }
  
  if (nchar(x) == 2) {a<- paste0('0', x)
  return(a)
  }
  else return(a)
}

home.list <- function(x) sapply(x, threedig)


 # function to extract a legend from one plot for use in whole plot grid
 # reference: https://stackoverflow.com/questions/13649473/add-a-common-legend-for-combined-ggplots
 g_legend<-function(a.gplot){
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)}
 

#Function to only display 3 significant figures (for tables)
signif3 <- function(x){
  signif(x, digits = 3)
}


# labeller

# make function to label metric names with subscripts and seasons
labeller.all <- as_labeller(c(
  'pm25'='PM[2.5]', 'voc'="TVOC",
  'co2' = 'CO[2]', 'temp' = 'Temperature', 'humid' = 'Humidity',
  'lux' = 'Light', 'spl_a' = 'Noise',
  'ac' = 'Cooling', 'shoulder' = 'Shoulder', 'heat' = 'Heating',
  'kitchen' = 'Kitchen', 'living' = 'Living', 'bedroom' = 'Bedroom',
  'outdoor' = 'Outdoor', 'garage'= 'Garage'
  ), default = label_parsed)
  
```




# define variables
```{r define_variables}

##For plot labeling pruposes
xsmall <- 6
small <- 15
medium <- 20
large <- 26
line_size <- 0.5
max_point_size <- 0.75

# define y-limits for metrics (for time series plots)
pm25_lim <- c(0,60)
voc_lim <- c(0,1500)
co2_lim <- c(0,2500)
temp_lim <- c(0,25)
humid_lim <- c(0,60)
lux_lim <- c(0,1000)
noise_lim <- c(40,70)


homes_all <- home.list(c(1:4, 6:16))


homes_tier1 <- home_type_df %>% filter(home_type == 'tier1') %>% pull(home)
homes_tier2 <- home_type_df %>% filter(home_type == 'tier2') %>% pull(home)
homes_tier3 <- home_type_df %>% filter(home_type == 'tier3') %>% pull(home)

#exclude homes with uncertain season classification
homes_seasons <- c(homes_tier2, homes_tier3)

metrics_all <- c('pm25', 'voc', 'co2', 'temp','humid', 'lux', 'spl_a')
locations_indoor <- c('living', 'bedroom', 'kitchen')

periods_all <- c('hour', 'day', 'month')


# color blind pallette
# check http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbbPalette <- c('black' = "#000000",
                'light_orange' = "#E69F00",
                'light_blue' = "#56B4E9",
                'green' = "#009E73",
                'yellow' = "#F0E442",
                'dark_blue' = "#0072B2",
                'dark_orange' = "#D55E00",
                'purple' = "#CC79A7"
                )
# define colors for room-comparisons
room_colors <- c(cbbPalette['green'],
                   cbbPalette['purple'],
                   cbbPalette['light_orange']
                   )%>% unname()

room_breaks <- locations_indoor

room_labels <- c('Living Room', 'Bedroom', 'Kitchen')

# define colors for energy clusters
energy_colors <- c(cbbPalette['light_blue'],
                   cbbPalette['green'],
                   cbbPalette['dark_orange'],
                   cbbPalette['black'])%>% unname()

energy_breaks <- c('ac', 'shoulder', 'heat', 'overall')
energy_labels <- c('Cooling', 'Shoulder', 'Heating', 'Entire Period')

time_colors <- c(cbbPalette['light_orange'],
                   cbbPalette['dark_blue']
                 )%>% unname()
time_breaks <- c('day', 'night')
time_labels <- c ('Day', 'Night')


```

# classify hourly data as night data or day data (not used)
```{r}
omni_hourly <- omni_hourly %>%
  mutate(hour = hour(datetime),
         time = case_when(hour >= 6 & hour <=20 ~ 'day',
                         hour < 6 | hour > 20 ~ 'night',
                         TRUE ~ 'time_error')
  )

```


# plot living room hourly values on x
# bedroom and kitchen hourly values on y


# plot function
```{r}


correl.plot <- function(x_met)
{

a <- omni_hourly %>%
  # filter(time == 'day') %>%
  filter(location %in% c('kitchen', 'living', 'bedroom')) %>% #only indoor
  select(-c(score, noise, lux, temp, humid))%>% #only pm, voc, co2
  pivot_longer(cols = c(co2:voc), names_to = 'metric') %>%
  pivot_wider( values_from = value, names_from = location) %>%
  pivot_longer( cols = c(kitchen, bedroom), names_to = 'location') %>%
  filter(metric == x_met) %>%
  filter(!is.na(value) & !is.na(living))

# calculate spearman correlation between living room
# and other two rooms for day and night
cor_df <- lapply( 
  c('kitchen', 'bedroom'),
       function(x) {
         
         data <- a %>% filter(location == x)
         
         n <- nrow(data)
         
         cor <- cor.test(
         data %>%  pull(living),
         data %>% pull(value),
         method = 'spearman',
         exact = FALSE # avoid error message, OK with approximate p value
         )
         
         results <- list(
           'location' = x,
           'rho' = cor$estimate,
           'p' = cor$p.value,
           'n_cor' = n,
           'n_lab' = formatC(n, format = 'd', big.mark = ',')
         )
       }
) %>%
  bind_rows() %>%
  # for label, code source:
  # https://stackoverflow.com/questions/27303019/ggplot-annotate-with-greek-symbol-and-1-apostrophe-or-2-in-between-text
  mutate(rho_label = sprintf( "rho == %0.2f", rho))


# define title depending on metric
if(x_met == 'pm25') metric_title <- expression(paste('PM'[2.5]))
   if(x_met == 'co2') metric_title <- expression(paste('CO'[2]))
   if(x_met == 'voc') metric_title <- 'TVOC'
   if(x_met == 'temp') metric_title <- 'Temperature'


# make the max x and y values whatever is the higheest value between all three rooms
max <- max( c(
  a %>%pull(value),
  a %>% pull(living)
), na.rm = TRUE )

#plot
ggplot(a, aes(x = living)) +
  geom_point(aes( y = value, color = location), size = 1)+
  # geom_raster( aes(y = kitchen, fill = after_stat(density)))
# stat_bin2d(aes(y = value,  fill = after_stat(count)), binwidth = c(5,5))+
  facet_wrap(
    vars(location),
             labeller = labeller.all
             )+
  theme_classic()+
  scale_x_continuous(limits = c(0, max))+
  scale_y_continuous(limits = c(0, max))+
  # add spearman rho into plot
  geom_text( data = cor_df,  aes(label = rho_label ),
             parse = T,
             x = 0.75*max, y = 0.3*max, size = 5)+
    geom_text( data = cor_df,  aes(label = paste0('n=', n_lab) ),
             x = 0.75*max, y = 0.17*max, size = 5)+
  scale_color_manual(
    values = room_colors[c(2:3)],
    breaks = room_breaks[c(2:3)],
    labels = room_labels[c(2:3)]
  )+
  ggtitle(metric_title)+
  ylab('Hourly Average\nConcentration')+
    xlab('Hourly Average Concentration in Living Room')+
  theme(
    legend.position = 'none',
    plot.title = element_text(hjust = 0.5 ),
      strip.text = element_text(size = small),
      axis.text = element_text(size = small-4),
      axis.title = element_text(size = small-1)
    )



}


  
```

# plot
```{r, fig.height=3, fig.width = 5}
# test for one mwtric
# correl.plot('pm25')

lapply(c( 'pm25',
          'voc', 
          'co2'
          ), function(x) correl.plot(x) )

```



# correlation for one metric and one room
```{r}
met <- 'voc'


a <- omni_hourly %>%
  # filter(time == 'day') %>%
  filter(location %in% c('kitchen', 'living', 'bedroom')) %>% #only indoor
  select(-c(score, noise, lux, temp, humid))%>% #only pm, voc, co2
  pivot_longer(cols = c(co2:voc), names_to = 'metric') %>%
  pivot_wider( values_from = value, names_from = location) %>%
  pivot_longer( cols = c(kitchen, bedroom), names_to = 'location') %>%
  filter(metric == met) %>%
  filter(!is.na(value) & !is.na(living))

# calculate spearman correlation between living room
# and other two rooms for day and night


         data <- a %>% filter(location == 'kitchen')
         
         n <- nrow(data)
         
         cor.test(
         data %>%  pull(living),
         data %>% pull(value),
         method = 'spearman',
         # exact = FALSE # avoid error message, OK with approximate p value
         )


  
```
