---
title: "UPAS"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

---

```{r}
source("../functions_epic.R")
```

```{r}
files <- list.files("../../data/upas", ".txt$", full.names = TRUE)
```

```{r}
upas_info_f <- function(file){read_csv(files, col_types = cols(), n_max = 4)}
```

---

# Sample Info

```{r}
sample_info_f <- function(file){
  read_csv(file, col_names = FALSE, col_types = cols(),
                       skip = 11, n_max = 3) %>%
  select(-X3) %>%
  pivot_wider(names_from = "X1", values_from = "X2") %>%
  rename_all(tolower) %>%
  mutate(id = str_sub(samplename, 1,3),
         location = gsub("_|-", "", str_sub(samplename, 4))) %>%
  rename(filter_id = "cartridgeid") %>%
  select(id, location, filter_id, upaslogfilename)
}
```

```{r}
sample_info <- map(files, sample_info_f) %>%
  bind_rows() 
```

---

# Setup Info

```{r}
setup_info_f <- function(file){
  read_csv(file, col_names = FALSE, col_types = cols(),
                     skip = 20, n_max = 13) %>%
  rename(var = "X1", val = "X2", units = "X3")
} 
```

---

# Summary

```{r}
summary_info_f <- function(file){
  read_csv(file, col_names = FALSE, col_types = cols(),
                       skip = 39, n_max = 12) %>%
  select(-"X3") %>%
  pivot_wider(names_from = "X1", values_from = "X2") %>%
  rename_all(tolower) %>%
  mutate(info = basename(file))
}
```

```{r}
summary_info <- map(files, summary_info_f) %>%
  bind_rows() %>%
  mutate(visit = gsub("^(.*)_(.*)_(.*)_(.*)(.txt$)", "\\2", info),
         visit = str_pad(sub("visit", "", visit), 2, "left", "0"),
         id_home = gsub("^(.*)_(.*)_(.*)_(.*)(.txt$)", "\\3", info),
         location = gsub("^(.*)_(.*)_(.*)_(.*)(.txt$)", "\\4", info)) %>%
  mutate_at(vars(contains("datetime")), upas_to_datetime) %>%
  select(-startdatetimeutc, -enddatetimeutc) %>%
  rename(start = "startdatetimelocal",
         end = "enddatetimelocal",
         volume = "sampledvolume",
         duration = "sampledruntime")
```

---

# Data

```{r}
data_f <- function(file){
  print(file)
  read_csv(file, col_names = TRUE, col_types = cols(.default = "c"),
                       skip = 59) %>%
  rename_all(tolower) %>%
  select(datetimelocal, volumetricflowrate, pumpt, pcbt, fdpt, bfgvolt) %>%
  rename(datetime = "datetimelocal", flow = "volumetricflowrate",
         battery = "bfgvolt") %>%
  mutate(datetime = sub("T"," ", datetime),
         datetime = as.POSIXct(strptime(datetime,
                                        format = "%Y-%m-%d %T",
                                        tz = "US/Mountain"))) %>%
  mutate_if(is.character, as.numeric) %>%
  mutate(battery = 100 * battery / 4,
         info = basename(file))
}
```

```{r}
data <- map(files, data_f) %>%
  bind_rows() %>%
  mutate(visit = gsub("^(.*)_(.*)_(.*)_(.*)(.txt$)", "\\2", info),
         id = gsub("^(.*)_(.*)_(.*)_(.*)(.txt$)", "\\3", info),
         location = gsub("^(.*)_(.*)_(.*)_(.*)(.txt$)", "\\4", info))
```

---

```{r, fig.width=12, fig.height=5}
ggplot(data, aes(x = datetime, y = battery, color = location)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~id, scales = "free") +
  ggtitle("Battery")
```

```{r, fig.width=12, fig.height=5}
ggplot(data, aes(x = datetime, y = fdpt, color = location)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~id, scales = "free") +
  ggtitle("Device Temperature") +
  ylab("Degrees C")
```

---

# Write Data

```{r}
write_rds(summary_info, "../output/upas_summary.rds")
write_rds(data, "../output/upas_data.rds")
```

