---
title: "Example of Extracting Probability Distribution"
author: "Andrew Purgiel"
date: "7/22/2021"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

---

```{r libraries}
library(dplyr)
library(purrr)
library(tidyr)
library(openair)
library(ggplot2)
library(readr)
library(googlesheets4)
library(lubridate)
library(gridExtra)
# library(tidymodels) # to discretize data for histogram
library(arules) # to discretize data for histogram
```

```{r data_import}
omni_hourly <- read_rds('./csv_created/omni_hourly_calibrated.rds') %>%
  rename(datetime = datehour)

home_type_df <- read_csv('../sense/csv_created_sense/home_type_df.csv')
```

# only use data up to June 2021
# and rename noise variable
```{r censor_date}
omni_hourly <- omni_hourly %>% filter(datetime<ymd_hms('2021-06-01 00:00:00'))%>%
  rename('noise' = spl_a)


```


```{r functions_misc}

 # misc------------------------------------------------

##Define a char vector of home numbers using a number vector,
##ex: x <- home.list(c(1:15)) for homes 1-15
threedig <- function(x) {
  if (nchar(x) == 1) {a <- paste0('00', x)
  return(a)
  }
  
  if (nchar(x) == 2) {a<- paste0('0', x)
  return(a)
  }
  else return(a)
}

home.list <- function(x) sapply(x, threedig)


 # function to extract a legend from one plot for use in whole plot grid
 # reference: https://stackoverflow.com/questions/13649473/add-a-common-legend-for-combined-ggplots
 g_legend<-function(a.gplot){
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)}
 



#Mean and sd functions to ignore NA values
mean_NA <- function(x, na.rm = na.rm) {
  mean(x, na.rm = TRUE)}

sd_NA <- function(x, na.rm = na.rm) {
  sd(x, na.rm = TRUE)}

#Function to only display 3 significant figures (for tables)
signif3 <- function(x){
  signif(x, digits = 3)
}



#Function found online for geometric mean to use for plots
#webpage: https://stackoverflow.com/questions/2602583/geometric-mean-is-there-a-built-in
#adjusted so zeros are not ignored, just added one, to all values and subtract at end
#adjusted "length" to ignore values that are NA


gm = function(x, na.rm=TRUE){
  if(any(x < 0, na.rm = TRUE)){
    return(NaN)
  }
  if(any(x == 0, na.rm = TRUE)){
    exp(sum(log(x+1), na.rm=na.rm) / length(x[!is.na(x)]))-1
  }
  else {
    exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x[!is.na(x)]))
  }
}



#make low and high sd "interval" functions
low.sd = function(x){
  mean_NA(x)-sd_NA(x)
}

high.sd = function(x){
  mean_NA(x)+sd_NA(x)
}


#create function for standard error
std.error = function(x, na.rm=TRUE){
  sd_NA(x)/sqrt(length(x[!is.na(x)]))
}

##make low and high 95% conf interval (default 95%)
low.conf = function(x){
  gm(x)-1.96*std.error(x)
}

high.conf = function(x){
  gm(x)+1.96*std.error(x)
}





# labeller

# make function to label metric names with subscripts and seasons
labeller.all <- as_labeller(c(
  'pm25'='PM[2.5]', 'voc'="TVOC",
  'co2' = 'CO[2]', 'temp' = 'Temperature', 'humid' = 'Humidity',
  'lux' = 'Light', 'spl_a' = 'Noise',
  'ac' = 'Cooling', 'shoulder' = 'Shoulder', 'heat' = 'Heating',
  'kitchen' = 'Kitchen', 'living' = 'Living', 'bedroom' = 'Bedroom',
  'outdoor' = 'Outdoor', 'garage'= 'Garage'
  ), default = label_parsed)
  
```



# define variables
```{r define_variables}

##For plot labeling pruposes
xsmall <- 6
small <- 15
medium <- 20
large <- 26
line_size <- 0.5
max_point_size <- 0.75

# define y-limits for metrics (for time series plots)
pm25_lim <- c(0,60)
voc_lim <- c(0,1500)
co2_lim <- c(0,2500)
temp_lim <- c(0,25)
humid_lim <- c(0,60)
lux_lim <- c(0,1000)
noise_lim <- c(40,70)

# define y-limits for metrics (for difference of means plots)
pm25_diff_lim <- c(-23,20)
voc_diff_lim <- c(-300,500)
co2_diff_lim <- c(-600,1250)
temp_diff_lim <- c(-5,3.5)
humid_diff_lim <- c(-9,9)
lux_diff_lim <- c(-500,750)
noise_diff_lim <- c(-9,9)

## for zoom:
#   pm25_lim <- c(0,40)
# voc_lim <- c(0,1000)
# co2_lim <- c(0,1500)
# temp_lim <- c(15,25)
# humid_lim <- c(20,60)
# lux_lim <- c(0,500)
# spl_a_lim <- c(40,70)




homes_all <- home.list(c(1:16))
homes_no5 <- home.list(c(1:4, 6:16))
homes_tier1 <- home_type_df %>% filter(home_type == 'tier1') %>% pull(home)
homes_tier2 <- home_type_df %>% filter(home_type == 'tier2') %>% pull(home)
homes_tier3 <- home_type_df %>% filter(home_type == 'tier3') %>% pull(home)

metrics_all <- c('pm25', 'voc', 'co2', 'temp','humid', 'lux', 'spl_a')
locations_indoor <- c('living', 'bedroom', 'kitchen')

periods_all <- c('hour', 'day', 'month')

living_data <- omni_hourly %>% filter(location == 'living')
kitchen_data <- omni_hourly %>% filter(location == 'kitchen')
bedroom_data <- omni_hourly %>% filter(location == 'bedroom')
outdoor_data <- omni_hourly %>% filter(location == 'outdoor')
garage_data <- omni_hourly %>% filter(location == 'garage')


# color blind pallette
# check http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbbPalette <- c('black' = "#000000",
                'light_orange' = "#E69F00",
                'light_blue' = "#56B4E9",
                'green' = "#009E73",
                'yellow' = "#F0E442",
                'dark_blue' = "#0072B2",
                'dark_orange' = "#D55E00",
                'purple' = "#CC79A7"
                )
# define colors for room-comparisons
room_colors <- c(cbbPalette['green'],
                   cbbPalette['purple'],
                   cbbPalette['light_orange']
                   )%>% unname()

room_breaks <- locations_indoor

room_labels <- c('Living Room', 'Bedroom', 'Kitchen')

# define colors for energy clusters
energy_colors <- c(cbbPalette['light_blue'],
                   cbbPalette['green'],
                   cbbPalette['dark_orange'],
                   cbbPalette['black'])%>% unname()

energy_breaks <- c('ac', 'shoulder', 'heat', 'overall')
energy_labels <- c('Cooling', 'Shoulder', 'Heating', 'Entire Period')
```




# make example time series plot and histograms

# show extraction process
# original (just season)
```{r, fig.height= 3, fig.width = 7}
a <- omni_hourly %>%
  filter(home == '009', location == 'living') %>%
  filter(datetime > '2020-9-27' & datetime < '2020-11-27') %>%
  mutate(hour = hour(datetime))

date_seq <- seq.POSIXt(min(a$datetime), max(a$datetime), by = '6 day') # make a sequence of sample cutoffs


x_labels <- date_seq+ days(3)
x_labels <- x_labels[1:(length(x_labels)-1)] # omit last value
labels <- 1:(length(x_labels))

ggplot()+
  geom_line(data = a, aes(y = pm25, x = datetime))+
  geom_segment(aes(x = date_seq,
                   xend = date_seq,
                   y = 0, yend = max(a$pm25)+10), color = cbbPalette['dark_orange'],
               size = 1)+
    geom_segment(aes(x = min(a$datetime),
               xend = max( date_seq),
               y = max(a$pm25)+10, yend = max(a$pm25)+10), color = cbbPalette['dark_orange'],
               size = 1)+
      geom_segment(aes(x = min(a$datetime),
               xend = max( date_seq),
               y = 0, yend = 0), color = cbbPalette['dark_orange'],
               size = 1)+
  geom_text(aes(x = x_labels, y = max(a$pm25)+5, label = labels), color = cbbPalette['dark_orange'])+
  theme_classic()+
  ylab(expression(paste('PM'[2.5], ', ug/m'^3)))+
  xlab('Date')



# show plot with just sample 5

ggplot()+
  geom_line(data = a, aes(y = pm25, x = datetime))+
  geom_rect(aes(xmin = date_seq[5], xmax = date_seq[6],
                   ymin = 0, ymax = max(a$pm25)+10),
            color = cbbPalette['dark_orange'], fill = NA,
               size = 1
            )+
  geom_text(
    aes(y = max(a$pm25)),
    x = date_seq[5]+ days(3), label = 'Sample', color = cbbPalette['dark_orange'])+
  theme_classic()+
  ylab(expression(paste('PM'[2.5], ', ug/m'^3)))+
  xlab('Date')






```

# show distributions
```{r, fig.height= 2, fig.width = 3}

# extract sample 5
sample_dat <- a %>%
  filter(datetime >= date_seq[5] & datetime < date_seq[6])

# make density histograms of magnitudes of sample 5 and entire monitoring period,
# ensuring to use the same bins for each
a_mag <- table(discretize(a$pm25, method = 'interval', breaks = 20))%>%
  data.frame() %>%
  mutate(Freq = Freq/sum(Freq, na.rm = TRUE)) %>%
  rename('longterm' = Freq)

pm_breaks <- discretize(a$pm25, method = 'interval', breaks = 20, onlycuts = TRUE)

sample_dat_mag <- table(discretize(sample_dat$pm25, method = 'fixed', breaks = pm_breaks)) %>%
  data.frame()%>%
  mutate(Freq = Freq/sum(Freq, na.rm = TRUE)) %>%
  rename('sample' = Freq)

data_mag <- a_mag %>%
  left_join(sample_dat_mag, by = 'Var1') %>%
  pivot_longer(cols = c(longterm, sample), names_to = 'origin', values_to = 'freq') %>%
  rename('bin' = Var1) %>%
  mutate(bin = gsub('^.*,|\\)$', '', bin),
         bin = gsub(']', '', bin),
         bin = as.numeric(bin))

# # plot method 1
# ggplot() +
#   geom_histogram(data = a, aes(x = pm25, y = ..density..),
#                  fill = 'black', alpha = 0.5)+
#   geom_histogram(data = sample_dat, aes(x = pm25, y = ..density..),
#                  fill = cbbPalette['dark_orange'], alpha = 0.5)+
#   theme_classic()+
#   xlab(expression(paste('PM'[2.5], ', ug/m'^3)))+
#   ylab('Density')+
#   theme(
#     axis.text.y = element_blank(),
#     axis.ticks.y = element_blank()
#   )

# plot method 2

ggplot() +
  geom_col(data = data_mag, aes(x = bin, y = freq, fill = origin),
           position = 'dodge')+
  theme_classic()+
  xlab(expression(paste('PM'[2.5], ', ug/m'^3)))+
  ylab('Density')+
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )+
  scale_fill_manual(
    breaks = c('longterm', 'sample'),
    labels = c('Entire Season', 'Sample'),
    values = c('black', cbbPalette['dark_orange'] %>%unname()),
    name = 'Data Set'
  )+
  theme(
    legend.position = 'none'
  )



# histogram of time values
a_hr <- a %>%
  group_by(hour) %>%
  summarise(mean = mean(pm25, na.rm = TRUE), .groups = 'drop') %>%
  mutate(origin = 'longterm')

sample_dat_hr <- sample_dat %>%
  group_by(hour) %>%
  summarise(mean = mean(pm25, na.rm = TRUE), .groups = 'drop') %>%
  mutate(origin = 'sample')

data_hr <- a_hr %>%
  rbind(sample_dat_hr)

ggplot() +
  geom_col(data = data_hr, aes(x = hour, y = mean, fill = origin),
                 position = 'dodge')+

  theme_classic()+
  ylab(expression(paste('Average PM'[2.5], ', ug/m'^3)))+
  scale_fill_manual(
    breaks = c('longterm', 'sample'),
    labels = c('Entire Season', 'Sample'),
    values = c('black', cbbPalette['dark_orange'] %>%unname()),
    name = 'Data Set'
  )+
  scale_x_continuous(
    breaks = c(0,6,12,18),
    labels = c('12am', '6am', '12pm', '6pm')
  )+
  xlab('Hour of Day')+
  theme(
    legend.position = 'none'
  )

```



# show entire monitoring period

```{r, fig.height= 3, fig.width = 7}
# make entire  monitoring period
a <- omni_hourly %>%
  filter(home == '006', location == 'living') %>%
  filter(datetime > '2020-8-27' & datetime < '2021-2-27') %>%
  mutate(hour = hour(datetime))

# make season start and end dates
season_start <- as.POSIXct('2020-9-27')
season_end <- as.POSIXct('2020-12-01')

sample_length <- 10

# make a sequence of sample cutoffs
date_seq <- seq.POSIXt(min(season_start), max(season_end), by = paste(sample_length, 'day'))


x_labels <- date_seq+ days(sample_length/2)
x_labels <- x_labels[1:(length(x_labels)-1)] # omit last value
labels <- 1:(length(x_labels))

ggplot()+
  #time series data
  geom_line(data = a, aes(y = pm25, x = datetime))+
  #vertical lines for sample boxes
  geom_segment(aes(x = date_seq,
                   xend = date_seq,
                   y = 0, yend = max(a$pm25)+5), color = cbbPalette['dark_orange'],
               size = 1)+
  #top horizontal line for sample boxes
    geom_segment(aes(x = min(season_start),
               xend = max( date_seq),
               y = max(a$pm25)+5, yend = max(a$pm25)+5), color = cbbPalette['dark_orange'],
               size = 1)+
  #bottom horizontal line for sample boxes
      geom_segment(aes(x = min(season_start),
               xend = max( date_seq),
               y = 0, yend = 0), color = cbbPalette['dark_orange'],
               size = 1)+
    #vertical lines for season start and end line for sample boxes
      geom_segment(aes(x = c(season_start, season_end),
               xend = c(season_start, season_end),
               y = 0, yend = max(a$pm25)+5), color = cbbPalette['dark_blue'],
               size = 1, linetype = 'dashed')+
  geom_text(aes(x = x_labels, y = max(a$pm25)+30, label = labels),
            color = cbbPalette['dark_orange'],
            size = small-6)+
  theme_classic()+
  ylab(expression(paste('PM'[2.5], ', ug/m'^3)))+
  xlab('Date')+
  scale_x_datetime(date_labels="%b",date_breaks  ="1 month")+
  theme(
    text = element_text(size = medium)
  )



# show plot with just sample 5

ggplot()+
  geom_line(data = a, aes(y = pm25, x = datetime))+
  geom_rect(aes(xmin = date_seq[5], xmax = date_seq[6],
                   ymin = 0, ymax = max(a$pm25)+5),
            color = cbbPalette['dark_orange'], fill = NA,
               size = 1
            )+
  geom_text(
    aes(y = max(a$pm25)+ 30),
    x = date_seq[5]+ days(sample_length/2), label = 'Sample',
    color = cbbPalette['dark_orange'],
    size = small - 8)+
  theme_classic()+
      #vertical lines for season start and end line for sample boxes
      geom_segment(aes(x = c(season_start, season_end),
               xend = c(season_start, season_end),
               y = 0, yend = max(a$pm25)+5), color = cbbPalette['dark_blue'],
               size = 1, linetype = 'dashed')+
  ylab(expression(paste('PM'[2.5], ', ug/m'^3)))+
  xlab('Date')+
  scale_x_datetime(date_labels="%b",date_breaks  ="1 month")+
  theme(
    text = element_text(size = medium)
  )






```


# show distributions
```{r, fig.height= 2, fig.width = 3}

# extract sample 3
sample_dat <- a %>%
  filter(datetime >= date_seq[3] & datetime < date_seq[4])

# make density histograms of magnitudes of sample 5 and entire monitoring period,
# ensuring to use the same bins for each
a_mag <- table(discretize(a$pm25, method = 'interval', breaks = 100))%>%
  data.frame() %>%
  mutate(Freq = Freq/sum(Freq, na.rm = TRUE)) %>%
  rename('longterm' = Freq)

pm_breaks <- discretize(a$pm25, method = 'interval', breaks = 100, onlycuts = TRUE)

sample_dat_mag <- table(discretize(sample_dat$pm25, method = 'fixed', breaks = pm_breaks)) %>%
  data.frame()%>%
  mutate(Freq = Freq/sum(Freq, na.rm = TRUE)) %>%
  rename('sample' = Freq)

data_mag <- a_mag %>%
  left_join(sample_dat_mag, by = 'Var1') %>%
  pivot_longer(cols = c(longterm, sample), names_to = 'origin', values_to = 'freq') %>%
  rename('bin' = Var1) %>%
  mutate(bin = gsub('^.*,|\\)$', '', bin),
         bin = gsub(']', '', bin),
         bin = as.numeric(bin))

# # plot method 1
# ggplot() +
#   geom_histogram(data = a, aes(x = pm25, y = ..density..),
#                  fill = 'black', alpha = 0.5)+
#   geom_histogram(data = sample_dat, aes(x = pm25, y = ..density..),
#                  fill = cbbPalette['dark_orange'], alpha = 0.5)+
#   theme_classic()+
#   xlab(expression(paste('PM'[2.5], ', ug/m'^3)))+
#   ylab('Density')+
#   theme(
#     axis.text.y = element_blank(),
#     axis.ticks.y = element_blank()
#   )

# plot method 2

ggplot() +
  geom_col(data = data_mag, aes(x = bin, y = freq, fill = origin),
           position = 'dodge')+
  theme_classic()+
  xlab(expression(paste('PM'[2.5], ', ug/m'^3)))+
  ylab('Density')+
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )+
  scale_fill_manual(
    breaks = c('longterm', 'sample'),
    labels = c('Entire Season', 'Sample'),
    values = c('black', cbbPalette['dark_orange'] %>%unname()),
    name = 'Data Set'
  )+
  theme(
    legend.position = 'none',
    text = element_text( size = medium)
  )+
  scale_x_continuous(
    limits = c(0,100) # make plot not so stretchy
  )



# histogram of time values
a_hr <- a %>%
  group_by(hour) %>%
  summarise(mean = mean(pm25, na.rm = TRUE), .groups = 'drop') %>%
  mutate(origin = 'longterm')

sample_dat_hr <- sample_dat %>%
  group_by(hour) %>%
  summarise(mean = mean(pm25, na.rm = TRUE), .groups = 'drop') %>%
  mutate(origin = 'sample')

data_hr <- a_hr %>%
  rbind(sample_dat_hr)

ggplot() +
  geom_col(data = data_hr, aes(x = hour, y = mean, fill = origin),
                 position = 'dodge')+

  theme_classic()+
  ylab(expression(paste('Average PM'[2.5], ', ug/m'^3)))+
  scale_fill_manual(
    breaks = c('longterm', 'sample'),
    labels = c('Entire Season', 'Sample'),
    values = c('black', cbbPalette['dark_orange'] %>%unname()),
    name = 'Data Set'
  )+
  scale_x_continuous(
    breaks = c(0,6,12,18),
    labels = c('12am', '6am', '12pm', '6pm')
  )+
  xlab('Hour of Day')+
  theme(
    legend.position = 'none'
  )+
  theme(
        text = element_text( size = medium-5),
        # axis.title = element_text(size = medium-4)
  )

```

