---
title: "Sense Explore"
output:
  html_document: default
  pdf_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/',
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 10, fig.height = 3,
  cache = FALSE)
```

```{r}
# reads source
source("../functions_epic.R")
```

```{r}
data <- read_rds("../output/sense_all.rds")
```

---

# Devices

```{r}
device_data <- data %>%
  select(job_id, datetime, device_id, sense_device_name, device_type) %>%
  filter(sense_device_name != "consumption" & sense_device_name != "always on") %>%
  pull(sense_device_name) %>%
  unique()

device_data
```

# Device Compumption Summary

```{r}
device_data <- data %>%
  filter(sense_device_name != "consumption" & sense_device_name != "always on") %>%
  select(job_id, datetime, sense_device_name, consumption_kwh) %>%
  mutate(date = as.Date(datetime),
         device = fct_collapse(sense_device_name, 
                             ac = c("ac", "ac 2"),
                             coffee = c("coffee maker", "coffee maker 2"),
                             drier = c("drier 1", "drier 2"),
                             heat = c("heat", "heat 1", "heat 2", "heat 3", "heat 4",
                                      "heat 5", "heat 6", "heat 7", "heat 8", "heat 9"),
                            light = c("light 1", "light 2", "light 3", "light 4", "light 5"),
                            pump = c("pump 1", "pump 2"),
                            dryer = c("dryer 1", "dryer 2"),
                             fridge = c("fridge 1", "fridge 2"),
                             stove = c("stove 1", "stove 2"),
                            unknown = c("device 1", "device 2"),
                             motor = c("motor 1", "motor 2"))) %>%
  group_by(job_id, date, device) %>%
  summarise(consumption = sum(consumption_kwh), .groups = "drop")
```

```{r}
ggplot(device_data, aes(x = date, y = consumption, fill = device)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  facet_wrap(~job_id, ncol = 4, scales = "free") +
  xlab("")
```

---

# write

```{r}
write_rds(data, "../output/sense_all.rds")
```


```{r}
grouped_data <- data

grouped_data$sense_device_name <- gsub("coffee maker","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("coffee maker 2","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("dishwasher","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("disposal","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("microwave","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("stove","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("stove 2","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("stove 3","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("kitchen appliances 1","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("kitchen appliances 2","kitchen appliances",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("oven","kitchen appliances",grouped_data$sense_device_name)

grouped_data$sense_device_name <- gsub("ac","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("ac","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("ac 2","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("furnace","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("fan","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("ventilation 2","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("ac","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("furnventilatione","ventilation",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("vventilationuum","ventilation",grouped_data$sense_device_name)

grouped_data$sense_device_name <- gsub("light 1","lighting",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("light 2","lighting",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("light 3","lighting",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("light 4","lighting",grouped_data$sense_device_name)


grouped_data$sense_device_name <- gsub("fridge 2","fridge",grouped_data$sense_device_name)

grouped_data$sense_device_name <- gsub("heat 1","heat",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("heat 2","heat",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("heat 3","heat",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("heat 4","heat",grouped_data$sense_device_name)
grouped_data$sense_device_name <- gsub("heat 5","heat",grouped_data$sense_device_name)

unique(grouped_data$sense_device_name)
```

```{r}
home_004 <- grouped_data %>%
  filter(job_id == "004")%>%
  filter(sense_device_name != "consumption" & sense_device_name != "always on")%>%
  mutate(date = as.Date(datetime))%>%
  select(job_id, datetime, sense_device_name, consumption_kwh)
```


```{r}
ggplot(home_004, aes(x = datetime, y = consumption_kwh)) +
  geom_line(aes(color = sense_device_name, linetype = sense_device_name))+
  ggtitle("Home 004")
```

